services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_WS_HOST=localhost:8080
    container_name: qualifyd-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_HOST=localhost:8080
      - NEXT_TELEMETRY_DISABLED=1
      - APP_ENV=dev
    depends_on:
      - backend
    networks:
      - qualifyd-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qualifyd-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TERMINAL_HOST=terminal
      - TERMINAL_PORT=22
      - TERMINAL_USER=candidate
      - TERMINAL_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=qualifyd
    depends_on:
      - db
      - terminal
    networks:
      - qualifyd-network
    restart: unless-stopped

  terminal:
    build:
      context: .
      dockerfile: Dockerfile.terminal
    container_name: qualifyd-terminal
    volumes:
      - terminal-data:/home/candidate/assessment
    networks:
      - qualifyd-network
    restart: unless-stopped
    ports:
      - "2222:22"

  db:
    image: postgres:17
    container_name: qualifyd-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qualifyd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - qualifyd-network
    restart: unless-stopped
    ports:
      - "5432:5432"

networks:
  qualifyd-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  terminal-data:
    driver: local
