apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: qualifyd-local
servers: 1
agents: 2
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5050"
