apiVersion: v1
kind: Pod
metadata:
  name: terminal-template
  namespace: qualifyd-dev
  labels:
    app.qualifyd.io/component: terminal
  annotations:
    description: "Template for terminal pods - not meant to be deployed directly"
    # This should be treated as a template only, not for direct deployment
    qualifyd.io/template: "true"
spec:
  # Important: This is just a template
  # When the backend creates pods dynamically, it will:
  # 1. Use this template as a base
  # 2. Set a different name with the assessment ID as a suffix
  # 3. Add appropriate labels and annotations
  containers:
    - name: terminal
      image: qualifyd-terminal:dev
      imagePullPolicy: Never  # Use local image for development
      ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      securityContext:
        # Note: We're intentionally not using runAsNonRoot here since the SSH server
        # in our image requires root to bind to port 22. The actual terminal user
        # that candidates will use is still a non-root 'candidate' user.
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        privileged: false
      readinessProbe:
        exec:
          command: ["/healthcheck.sh"]
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      livenessProbe:
        exec:
          command: ["/healthcheck.sh"]
        initialDelaySeconds: 15
        periodSeconds: 20
        timeoutSeconds: 5
        failureThreshold: 3
  restartPolicy: Never
