apiVersion: v1
kind: Pod
metadata:
  name: terminal-template
  namespace: qualifyd-dev
  labels:
    app.qualifyd.io/component: terminal
  annotations:
    description: "Template for terminal pods - not meant to be deployed directly"
spec:
  containers:
    - name: terminal
      image: qualifyd-terminal:dev
      imagePullPolicy: Never  # Use local image for development
      ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        privileged: false
      readinessProbe:
        exec:
          command: ["/healthcheck.sh"]
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      livenessProbe:
        exec:
          command: ["/healthcheck.sh"]
        initialDelaySeconds: 15
        periodSeconds: 20
        timeoutSeconds: 5
        failureThreshold: 3
  restartPolicy: Never
