apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: qualifyd-dev
data:
  config.yaml: |
    server:
      port: 8080
      host: "0.0.0.0"
      cors:
        allowedOrigins:
          - "http://localhost:3000"
          - "https://localhost:3000"
        allowCredentials: true

    database:
      host: "postgresql.qualifyd-dev.svc.cluster.local"
      port: 5432
      name: "qualifyd"
      user: "qualifyd"
      sslMode: "disable"

    rabbitmq:
      host: "rabbitmq.qualifyd-dev.svc.cluster.local"
      port: 5672
      user: "qualifyd"
      vhost: "/"

    log:
      level: "debug"
      format: "json"
