apiVersion: v1
kind: ConfigMap
metadata:
  name: terminal-templates
  namespace: qualifyd-dev
data:
  default.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: terminal-template
      labels:
        app.qualifyd.io/component: terminal
      annotations:
        description: "Default terminal environment"
    spec:
      containers:
        - name: terminal
          image: qualifyd-terminal:dev
          imagePullPolicy: Never
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            privileged: false
          readinessProbe:
            exec:
              command: ["/healthcheck.sh"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["/healthcheck.sh"]
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Never

  kubernetes.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: terminal-template
      labels:
        app.qualifyd.io/component: terminal
      annotations:
        description: "Kubernetes environment with kubectl and helm"
    spec:
      containers:
        - name: terminal
          image: qualifyd-terminal:dev
          imagePullPolicy: Never
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            privileged: false
          volumeMounts:
            - name: kube-config
              mountPath: /home/candidate/.kube
              readOnly: true
          readinessProbe:
            exec:
              command: ["/healthcheck.sh"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["/healthcheck.sh"]
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: kube-config
          configMap:
            name: candidate-kubeconfig
      restartPolicy: Never
