apiVersion: v1
kind: ServiceAccount
metadata:
  name: poc-backend
  namespace: qualifyd-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: qualifyd-dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poc-backend-pod-reader
  namespace: qualifyd-dev
subjects:
- kind: ServiceAccount
  name: poc-backend
  namespace: qualifyd-dev
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-backend
  namespace: qualifyd-dev
  labels:
    app: poc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-backend
  template:
    metadata:
      labels:
        app: poc-backend
    spec:
      serviceAccountName: poc-backend
      containers:
      - name: backend
        image: poc-backend:latest
        imagePullPolicy: Never # For local development
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 65534  # This is the numeric ID for 'nobody'
          capabilities:
            drop: ["ALL"]
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: poc-backend
  namespace: qualifyd-dev
spec:
  selector:
    app: poc-backend
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP
